CREATE TABLE `aws_customer_subscriber_annual_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_aws_account_number` varchar(16) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_id` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `subscription_id` varchar(16) NOT NULL,
  `subscription_quantity` int(11) NOT NULL,
  `subscription_type` varchar(128) DEFAULT NULL,
  `subscription_start_date` date NOT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `subscription_end_date` date NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1063 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_customer_subscriber_hourly_monthly_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_aws_account_number` varchar(16) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_id` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `subscription_start_date` date NOT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25004 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_canceled_product_subscribers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `users_state` varchar(32) DEFAULT NULL,
  `users_country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `subscribed_date` date NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_country` varchar(2) DEFAULT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) DEFAULT NULL,
  `customer_zip_code` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_fees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `users_state` varchar(32) DEFAULT NULL,
  `users_country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `fee_description` varchar(64) DEFAULT NULL,
  `customer_aws_account_number` varchar(16) NOT NULL,
  `customer_country` varchar(2) NOT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) NOT NULL,
  `customer_zip_code` varchar(16) NOT NULL,
  `customer_email_domain` varchar(128) NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `dimension` varchar(64) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_free_trial_conversions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `new_free_trials` int(11) NOT NULL,
  `total_current_free_trials` int(11) NOT NULL,
  `converted_free_trials` int(11) NOT NULL,
  `nonconverted_free_trials` int(11) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=297 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_new_instances` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `users_state` varchar(32) DEFAULT NULL,
  `users_country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `type` varchar(16) NOT NULL,
  `count` int(11) NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_country` varchar(2) DEFAULT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) DEFAULT NULL,
  `customer_zip_code` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=304 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_new_product_subscribers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `users_state` varchar(32) DEFAULT NULL,
  `users_country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_country` varchar(2) DEFAULT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) DEFAULT NULL,
  `customer_zip_code` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_daily_business_usage_by_instance_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `users_state` varchar(32) DEFAULT NULL,
  `users_country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `instance_type` varchar(16) NOT NULL,
  `usage_units` int(11) NOT NULL,
  `usage_unit_types` varchar(16) NOT NULL,
  `offering_description` varchar(16) NOT NULL,
  `estimated_revenue` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_country` varchar(2) DEFAULT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) DEFAULT NULL,
  `customer_zip_code` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `offer_id` varchar(32) DEFAULT NULL,
  `offer_visibility` varchar(16) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3837 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_age_of_disbursed_funds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `collected_under_31_days_pending` decimal(10,2) NOT NULL,
  `collected_31_60_days_pending` decimal(10,2) NOT NULL,
  `collected_61_90_days_pending` decimal(10,2) NOT NULL,
  `collected_91_120_days_pending` decimal(10,2) NOT NULL,
  `collected_over_120_days_pending` decimal(10,2) NOT NULL,
  `collected_overall` decimal(10,2) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_age_of_past_due_funds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `past_due_under_31_days` decimal(10,2) NOT NULL,
  `past_due_31_60_days` decimal(10,2) NOT NULL,
  `past_due_61_90_days` decimal(10,2) NOT NULL,
  `past_due_91_120_days` decimal(10,2) NOT NULL,
  `past_due_over_120_days` decimal(10,2) NOT NULL,
  `past_due_overall` decimal(10,2) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_age_of_uncollected_funds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uncollected_under_31_days_pending` decimal(10,2) NOT NULL,
  `uncollected_31_60_days_pending` decimal(10,2) NOT NULL,
  `uncollected_61_90_days_pending` decimal(10,2) NOT NULL,
  `uncollected_91_120_days_pending` decimal(10,2) NOT NULL,
  `uncollected_over_120_days_pending` decimal(10,2) NOT NULL,
  `uncollected_overall` decimal(10,2) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_customer_geo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `settlement_id` varchar(256) DEFAULT NULL,
  `settlement_period_start_date` datetime DEFAULT NULL,
  `settlement_period_end_date` datetime DEFAULT NULL,
  `deposit_date` datetime DEFAULT NULL,
  `disbursed_amount` decimal(10,2) DEFAULT NULL,
  `country_code` varchar(2) DEFAULT NULL,
  `state_or_region` varchar(32) DEFAULT NULL,
  `city` varchar(32) DEFAULT NULL,
  `postal_code` varchar(32) DEFAULT NULL,
  `net_amount_by_tax_location` decimal(10,2) DEFAULT NULL,
  `gross_amount_by_tax_location` decimal(10,2) DEFAULT NULL,
  `seller_us_sales_tax` decimal(10,2) DEFAULT NULL,
  `seller_us_sales_tax_refund` decimal(10,2) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_instance_hours` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product` varchar(64) DEFAULT NULL,
  `product_code` varchar(32) NOT NULL,
  `usage_type_description` varchar(128) DEFAULT NULL,
  `rate` decimal(10,2) NOT NULL,
  `user_count` int(11) NOT NULL,
  `instance_hours` decimal(10,2) NOT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=139 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product` varchar(64) DEFAULT NULL,
  `product_code` varchar(32) NOT NULL,
  `sellerrev` decimal(10,2) NOT NULL,
  `awsreffee` decimal(10,2) NOT NULL,
  `sellerrevrefund` decimal(10,2) NOT NULL,
  `awsreffeerefund` decimal(10,2) NOT NULL,
  `sellerrevcredit` decimal(10,2) NOT NULL,
  `awsreffeecredit` decimal(10,2) NOT NULL,
  `cost` decimal(10,2) NOT NULL,
  `net_amount` decimal(10,2) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `sellerussalestax` decimal(10,2) NOT NULL,
  `sellerussalestaxrefund` decimal(10,2) NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_country` varchar(2) DEFAULT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) DEFAULT NULL,
  `customer_zip_code` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_disbursed_amount_by_uncollected_funds_breakdown` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_code` varchar(32) NOT NULL,
  `product` varchar(64) DEFAULT NULL,
  `sellerrev` decimal(10,2) NOT NULL,
  `awsreffee` decimal(10,2) NOT NULL,
  `sellerrevrefund` decimal(10,2) NOT NULL,
  `awsreffeerefund` decimal(10,2) NOT NULL,
  `net_amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `ar_period` varchar(7) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `opportunity_name` varchar(64) DEFAULT NULL,
  `opportunity_description` varchar(64) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `payment_due_date` date NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_monthly_revenue_annual_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_reference_id` varchar(16) NOT NULL,
  `country` varchar(2) NOT NULL,
  `state` varchar(32) DEFAULT NULL,
  `city` varchar(32) NOT NULL,
  `zip_code` varchar(16) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `subscription_quantity` int(11) NOT NULL,
  `subscription_start_date` date NOT NULL,
  `subscription_end_date` date NOT NULL,
  `subscription_instance_type` varchar(16) NOT NULL,
  `customer_billed_amount` decimal(10,2) NOT NULL,
  `aws_fee` decimal(10,2) NOT NULL,
  `refunds_amount` decimal(10,2) NOT NULL,
  `aws_fee_refund` decimal(10,2) NOT NULL,
  `cost` decimal(10,2) NOT NULL,
  `partner_revenue_amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `us_sales_tax_customer_billed_amount` decimal(10,2) NOT NULL,
  `us_sales_tax_refunds_amount` decimal(10,2) NOT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `contract_start_date` date NOT NULL,
  `contract_end_date` date NOT NULL,
  `opportunity_name` varchar(64) DEFAULT NULL,
  `opportunity_description` varchar(64) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_monthly_revenue_billing_and_revenue_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country` varchar(2) NOT NULL,
  `state` varchar(32) DEFAULT NULL,
  `city` varchar(32) NOT NULL,
  `zip_code` varchar(16) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `customer_billed_amount` decimal(10,2) NOT NULL,
  `aws_fee` decimal(10,2) NOT NULL,
  `refunds_amount` decimal(10,2) NOT NULL,
  `aws_fee_refund` decimal(10,2) NOT NULL,
  `cost` decimal(10,2) NOT NULL,
  `partner_revenue_amount` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `us_sales_tax_customer_billed_amount` decimal(10,2) NOT NULL,
  `us_sales_tax_refunds_amount` decimal(10,2) NOT NULL,
  `customer_aws_account_number` varchar(16) DEFAULT NULL,
  `customer_email_domain` varchar(128) DEFAULT NULL,
  `offer_id` varchar(32) NOT NULL,
  `offer_visibility` varchar(16) NOT NULL,
  `opportunity_name` varchar(64) DEFAULT NULL,
  `opportunity_description` varchar(64) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=120 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_monthly_revenue_field_demonstration_usage` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country` varchar(2) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `instance_type` varchar(16) NOT NULL,
  `usage_units` int(11) NOT NULL,
  `usage_unit_types` varchar(16) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_monthly_revenue_flexible_payment_schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_aws_account_number` varchar(16) NOT NULL,
  `customer_country` varchar(2) NOT NULL,
  `customer_state` varchar(32) DEFAULT NULL,
  `customer_city` varchar(32) NOT NULL,
  `customer_zip_code` varchar(16) NOT NULL,
  `customer_email_domain` varchar(128) NOT NULL,
  `user_reference_id` varchar(64) NOT NULL,
  `user_aws_account_number` varchar(16) NOT NULL,
  `product_id` varchar(64) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `product_type` varchar(64) NOT NULL,
  `aws_marketplace_offer_id` varchar(64) NOT NULL,
  `contract_create_date` date NOT NULL,
  `contract_expiration_date` date NOT NULL,
  `total_contract_value_usd` decimal(10,2) NOT NULL,
  `number_of_payments` int(11) NOT NULL,
  `invoice_date` date NOT NULL,
  `invoice_amount_usd` decimal(10,2) NOT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_sales_compensation_billed_revenue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_aws_account_number` varchar(16) NOT NULL,
  `country` varchar(2) NOT NULL,
  `state` varchar(32) DEFAULT NULL,
  `city` varchar(32) NOT NULL,
  `zip_code` varchar(16) NOT NULL,
  `email_domain` varchar(128) NOT NULL,
  `product_code` varchar(32) NOT NULL,
  `product_title` varchar(64) NOT NULL,
  `gross_revenue` decimal(10,2) NOT NULL,
  `aws_revenue_share` decimal(10,2) NOT NULL,
  `gross_refunds` decimal(10,2) NOT NULL,
  `aws_refunds_share` decimal(10,2) NOT NULL,
  `net_revenue` decimal(10,2) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `ar_period` varchar(7) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `opportunity_name` varchar(64) DEFAULT NULL,
  `opportunity_description` varchar(64) DEFAULT NULL,
  `solution_title` varchar(64) DEFAULT NULL,
  `solution_id` varchar(64) DEFAULT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `payer_address_id` varchar(64) DEFAULT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aws_us_sales_and_use_tax_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `line_item_id` varchar(32) NOT NULL,
  `customer_bill_id` varchar(32) NOT NULL,
  `product_name` varchar(64) DEFAULT NULL,
  `product_code` varchar(32) NOT NULL,
  `product_tax_code` varchar(64) DEFAULT NULL,
  `seller_id` varchar(64) DEFAULT NULL,
  `seller_name` varchar(64) DEFAULT NULL,
  `transaction_date` date NOT NULL,
  `total_adjusted_price` decimal(10,2) NOT NULL,
  `total_tax` decimal(10,2) NOT NULL,
  `base_currency_code` varchar(3) NOT NULL,
  `bill_to_city` varchar(32) NOT NULL,
  `bill_to_state` varchar(32) NOT NULL,
  `bill_to_postal_code` varchar(32) NOT NULL,
  `bill_to_country` varchar(2) NOT NULL,
  `transaction_type_code` varchar(32) NOT NULL,
  `display_price_taxability_type` varchar(32) NOT NULL,
  `tax_location_code_taxed_jurisdiction` varchar(32) NOT NULL,
  `tax_type_code` varchar(32) NOT NULL,
  `jurisdiction_level` varchar(32) NOT NULL,
  `taxed_jurisdiction` varchar(64) NOT NULL,
  `taxable_sale_amount` decimal(10,2) NOT NULL,
  `nontaxable_sale_amount` decimal(10,2) NOT NULL,
  `tax_amount` decimal(10,2) NOT NULL,
  `tax_jurisdiction_tax_rate` decimal(10,9) NOT NULL,
  `tax_calculation_reason_code` varchar(32) NOT NULL,
  `date_used_for_tax_calculation` date NOT NULL,
  `customer_exemption_certificate_id` varchar(64) DEFAULT NULL,
  `customer_exemption_certificate_id_domain` varchar(64) DEFAULT NULL,
  `customer_exemption_certificate_level` varchar(64) DEFAULT NULL,
  `customer_exemption_code` varchar(64) DEFAULT NULL,
  `customer_exemption_domain` varchar(64) DEFAULT NULL,
  `customer_reference_id` varchar(16) NOT NULL,
  `transaction_reference_id` varchar(64) NOT NULL,
  `payer_reference_id` varchar(16) NOT NULL,
  `tax_liable_party` varchar(32) NOT NULL,
  `effective_date` date NOT NULL,
  `current` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=503 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;